---

language: python
services: docker

env:
  - distro: ubuntu1404
    cleanup: false
    port: '127.0.0.1:4444:4444'

script:
  - ${PWD}/tests/test.sh
  - pip install selenium
  - python ${PWD}/tests/test.py
